/*
 * Author Roger G. Coscojuela
 */
package vista;

import controlador.Client_Controller;
import controlador.Vehicle_Controller;
import java.util.List;
import javax.persistence.NoResultException;
import javax.persistence.PersistenceException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Adreca;
import modelo.Client;
import modelo.Vehicle;

/**
 *
 * @author Roger G. Coscojuela
 */
public class inicia extends javax.swing.JFrame {

    /**
     * Creates new form inicia
     */
    public inicia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        eTNom = new javax.swing.JTextField();
        eTNif = new javax.swing.JTextField();
        eTCarrer = new javax.swing.JTextField();
        eTNumero = new javax.swing.JTextField();
        eTPoblacio = new javax.swing.JTextField();
        btBuscarXNom = new javax.swing.JButton();
        btBuscarTotsClients = new javax.swing.JButton();
        btInserir = new javax.swing.JButton();
        btModificar = new javax.swing.JButton();
        btEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        eTMatricula = new javax.swing.JTextField();
        eTMarca = new javax.swing.JTextField();
        eTAnyMatriculacio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        eTDNIPropietari = new javax.swing.JTextField();
        btBuscarXMatricula = new javax.swing.JButton();
        btInserirVehicle = new javax.swing.JButton();
        btModificarVehicle = new javax.swing.JButton();
        btEliminarVehicle = new javax.swing.JButton();
        btMostrarTotsVehicles = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nom");

        jLabel2.setText("Nif");

        jLabel3.setText("Carrer");

        jLabel4.setText("Numero");

        jLabel5.setText("Poblacio");

        btBuscarXNom.setText("Buscar per Nif");
        btBuscarXNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarXNomActionPerformed(evt);
            }
        });

        btBuscarTotsClients.setText("Buscar Tots");
        btBuscarTotsClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarTotsClientsActionPerformed(evt);
            }
        });

        btInserir.setText("Inserir");
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });

        btModificar.setText("Modificar");
        btModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarActionPerformed(evt);
            }
        });

        btEliminar.setText("Eliminar");
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nom", "Nif", "Carrer", "Numero", "Població"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(4).setHeaderValue("Població");
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eTNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(eTCarrer)
                            .addComponent(eTNom)
                            .addComponent(eTNif)
                            .addComponent(eTPoblacio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btBuscarXNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btBuscarTotsClients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btInserir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(77, 77, 77))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(eTNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarXNom))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(eTNif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btInserir))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(eTCarrer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btModificar))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(eTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEliminar))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(eTPoblacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarTotsClients))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("Clients", jPanel4);

        jLabel6.setText("Matricula");

        jLabel7.setText("Marca");

        jLabel8.setText("Any Matriculacio");

        jLabel9.setText("DNI propietari");

        btBuscarXMatricula.setText("Buscar per Matricula");
        btBuscarXMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarXMatriculaActionPerformed(evt);
            }
        });

        btInserirVehicle.setText("Inserir");
        btInserirVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirVehicleActionPerformed(evt);
            }
        });

        btModificarVehicle.setText("Modificar");
        btModificarVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarVehicleActionPerformed(evt);
            }
        });

        btEliminarVehicle.setText("Eliminar");
        btEliminarVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarVehicleActionPerformed(evt);
            }
        });

        btMostrarTotsVehicles.setText("Mostrar Tots");
        btMostrarTotsVehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarTotsVehiclesActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Matricula", "Marca", "Any Matriculacio", "DNI Propietari"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eTDNIPropietari, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(eTAnyMatriculacio)
                    .addComponent(eTMarca)
                    .addComponent(eTMatricula))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btBuscarXMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btInserirVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btModificarVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btEliminarVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btMostrarTotsVehicles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eTMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btBuscarXMatricula))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eTMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eTAnyMatriculacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btInserirVehicle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btModificarVehicle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btEliminarVehicle)))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btMostrarTotsVehicles)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(eTDNIPropietari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("Vehicle", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarXNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarXNomActionPerformed
        Client_Controller client_Control = new Client_Controller();
        try {
            Client c = client_Control.Buscar(eTNif.getText());
            eTNom.setText(c.getNom());
            eTNif.setText(c.getNif());
            eTCarrer.setText(c.getAdreca().getCarrer());
            eTNumero.setText(String.valueOf(c.getAdreca().getNumero()));
            eTPoblacio.setText(c.getAdreca().getPoblacio());
        } catch (NoResultException ex) {
            JOptionPane.showMessageDialog(this, "Sense resultats");
        }


    }//GEN-LAST:event_btBuscarXNomActionPerformed

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed
        Client_Controller client_Control = new Client_Controller();
        try {
            Client client = client_Control.Buscar(eTNif.getText());
            client_Control.Eliminar(client);
            JOptionPane.showMessageDialog(this, "Eliminat");

        } catch (PersistenceException ex) {
            JOptionPane.showMessageDialog(this, "Fallo.");
        }
    }//GEN-LAST:event_btEliminarActionPerformed

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed
        Adreca adreca = new Adreca(eTCarrer.getText(), Integer.parseInt(eTNumero.getText()), eTPoblacio.getText());
        Client client = new Client(eTNif.getText(), eTNom.getText());
        client.setAdreca(adreca);
        Client_Controller client_Control = new Client_Controller();

        try {
            client_Control.Insertar(client);
            JOptionPane.showMessageDialog(this, "Inserit");

        } catch (PersistenceException ex) {
            JOptionPane.showMessageDialog(this, "Fallo. Elemento duplicado");
        }
    }//GEN-LAST:event_btInserirActionPerformed

    private void btModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarActionPerformed
        Client_Controller client_Control = new Client_Controller();
        try {
            Client client = client_Control.Buscar(eTNif.getText());
            client.setAdreca(new Adreca(eTCarrer.getText(), Integer.valueOf(eTNumero.getText()), eTPoblacio.getText()));
            client.setNom(eTNom.getText());
            client_Control.Modificar(client);
        } catch (NoResultException ex) {
            JOptionPane.showMessageDialog(this, "Sense resultats");
        }
    }//GEN-LAST:event_btModificarActionPerformed

    private void btBuscarTotsClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarTotsClientsActionPerformed
        Client_Controller pc = new Client_Controller();
        List<Client> ConsultaTots = pc.ConsultaTots();
        String col[] = {"Nom", "Nif", "Carrer", "Numero", "Poblacio"};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0);
        for (Client p : ConsultaTots) {
            Object[] data = {
                p.getNom(),
                p.getNif(),
                p.getAdreca().getCarrer(),
                p.getAdreca().getNumero(),
                p.getAdreca().getPoblacio()
            };
            tableModel.addRow(data);
        }
        jTable1.setModel(tableModel);
    }//GEN-LAST:event_btBuscarTotsClientsActionPerformed

    private void btBuscarXMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarXMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btBuscarXMatriculaActionPerformed

    private void btInserirVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirVehicleActionPerformed
        int LLARGADA_MAXIMA_MATRICULA = 7;
        if (eTMatricula.getText().length() < LLARGADA_MAXIMA_MATRICULA) {
            Vehicle_Controller vc = new Vehicle_Controller();
            Client_Controller cc = new Client_Controller();
            try {
                Client propietari = cc.Buscar(eTDNIPropietari.getText());
                Vehicle v = new Vehicle(eTMatricula.getText(), eTMarca.getText(), Integer.valueOf(eTAnyMatriculacio.getText()), propietari);
                vc.Insertar(v);
                JOptionPane.showMessageDialog(this, "Inserit");
            } catch (NoResultException ex) {
                JOptionPane.showMessageDialog(this, "Error. No existeix aquest propietari a la BBDD");
            } catch (PersistenceException ex) {
                JOptionPane.showMessageDialog(this, "Error. Element duplicat");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "La matricula pot tenir un maxim de 7 caracters"); 
        }


    }//GEN-LAST:event_btInserirVehicleActionPerformed

    private void btModificarVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarVehicleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btModificarVehicleActionPerformed

    private void btEliminarVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarVehicleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEliminarVehicleActionPerformed

    private void btMostrarTotsVehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarTotsVehiclesActionPerformed
        Vehicle_Controller vc = new Vehicle_Controller();
        List<Vehicle> ConsultaTots = vc.ConsultaTots();
        String col[] = {"Matricula", "Marca", "Any Matriculació", "DNI Propietari"};
        DefaultTableModel tableModel2 = new DefaultTableModel(col, 0);
        for (Vehicle v : ConsultaTots) {
            Object[] data = {
                v.getMatricula(),
                v.getMarca(),
                String.valueOf(v.getAnyMatriculacio()),
                v.getPropietari().getNif()
            };
            tableModel2.addRow(data);
        }
        jTable2.setModel(tableModel2);
    }//GEN-LAST:event_btMostrarTotsVehiclesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarTotsClients;
    private javax.swing.JButton btBuscarXMatricula;
    private javax.swing.JButton btBuscarXNom;
    private javax.swing.JButton btEliminar;
    private javax.swing.JButton btEliminarVehicle;
    private javax.swing.JButton btInserir;
    private javax.swing.JButton btInserirVehicle;
    private javax.swing.JButton btModificar;
    private javax.swing.JButton btModificarVehicle;
    private javax.swing.JButton btMostrarTotsVehicles;
    private javax.swing.JTextField eTAnyMatriculacio;
    private javax.swing.JTextField eTCarrer;
    private javax.swing.JTextField eTDNIPropietari;
    private javax.swing.JTextField eTMarca;
    private javax.swing.JTextField eTMatricula;
    private javax.swing.JTextField eTNif;
    private javax.swing.JTextField eTNom;
    private javax.swing.JTextField eTNumero;
    private javax.swing.JTextField eTPoblacio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
