/*
 * Author Roger G. Coscojuela
 */
package vista;

import controlador.Client_Controller;
import controlador.Polissa_Controller;
import controlador.Vehicle_Controller;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.NoResultException;
import javax.persistence.PersistenceException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Adreca;
import modelo.Client;
import modelo.Polissa;
import modelo.Vehicle;

/**
 *
 * @author Roger G. Coscojuela
 */
public class inicia extends javax.swing.JFrame {

    
    
    /**
     * Creates new form inicia
     */
    public inicia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        eTNom = new javax.swing.JTextField();
        eTNif = new javax.swing.JTextField();
        eTCarrer = new javax.swing.JTextField();
        eTNumero = new javax.swing.JTextField();
        eTPoblacio = new javax.swing.JTextField();
        btBuscarXNom = new javax.swing.JButton();
        btBuscarTotsClients = new javax.swing.JButton();
        btInserir = new javax.swing.JButton();
        btModificar = new javax.swing.JButton();
        btEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        eTMatricula = new javax.swing.JTextField();
        eTMarca = new javax.swing.JTextField();
        eTAnyMatriculacio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        eTDNIPropietari = new javax.swing.JTextField();
        btBuscarXMatricula = new javax.swing.JButton();
        btInserirVehicle = new javax.swing.JButton();
        btModificarVehicle = new javax.swing.JButton();
        btEliminarVehicle = new javax.swing.JButton();
        btMostrarTotsVehicles = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        eTNumeroPolissa = new javax.swing.JTextField();
        eTDNIPrenedor = new javax.swing.JTextField();
        eTPolissaMatriculaVehicle = new javax.swing.JTextField();
        eTDataInici = new javax.swing.JTextField();
        eTDataFi = new javax.swing.JTextField();
        cbTipusPolissa = new javax.swing.JComboBox();
        btBuscarXNumPolissa = new javax.swing.JButton();
        btInserirPolissa = new javax.swing.JButton();
        btModificarPolissa = new javax.swing.JButton();
        btEliminarPolissa = new javax.swing.JButton();
        btMostrarTotesPolisses = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        eTPrima = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nom");

        jLabel2.setText("Nif");

        jLabel3.setText("Carrer");

        jLabel4.setText("Numero");

        jLabel5.setText("Poblacio");

        btBuscarXNom.setText("Buscar per Nif");
        btBuscarXNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarXNomActionPerformed(evt);
            }
        });

        btBuscarTotsClients.setText("Buscar Tots");
        btBuscarTotsClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarTotsClientsActionPerformed(evt);
            }
        });

        btInserir.setText("Inserir");
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });

        btModificar.setText("Modificar");
        btModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarActionPerformed(evt);
            }
        });

        btEliminar.setText("Eliminar");
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nom", "Nif", "Carrer", "Numero", "Població"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(4).setHeaderValue("Població");
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eTNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(eTCarrer)
                            .addComponent(eTNom)
                            .addComponent(eTNif)
                            .addComponent(eTPoblacio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btBuscarXNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btBuscarTotsClients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btInserir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(77, 77, 77))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(eTNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarXNom))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(eTNif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btInserir))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(eTCarrer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btModificar))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(eTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEliminar))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(eTPoblacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarTotsClients))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("Clients", jPanel4);

        jLabel6.setText("Matricula");

        jLabel7.setText("Marca");

        jLabel8.setText("Any Matriculacio");

        jLabel9.setText("DNI propietari");

        btBuscarXMatricula.setText("Buscar per Matricula");
        btBuscarXMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarXMatriculaActionPerformed(evt);
            }
        });

        btInserirVehicle.setText("Inserir");
        btInserirVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirVehicleActionPerformed(evt);
            }
        });

        btModificarVehicle.setText("Modificar");
        btModificarVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarVehicleActionPerformed(evt);
            }
        });

        btEliminarVehicle.setText("Eliminar");
        btEliminarVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarVehicleActionPerformed(evt);
            }
        });

        btMostrarTotsVehicles.setText("Mostrar Tots");
        btMostrarTotsVehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarTotsVehiclesActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Matricula", "Marca", "Any Matriculacio", "DNI Propietari"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eTDNIPropietari, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(eTAnyMatriculacio)
                    .addComponent(eTMarca)
                    .addComponent(eTMatricula))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btBuscarXMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btInserirVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btModificarVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btEliminarVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btMostrarTotsVehicles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eTMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btBuscarXMatricula))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eTMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eTAnyMatriculacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btInserirVehicle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btModificarVehicle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btEliminarVehicle)))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btMostrarTotsVehicles)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(eTDNIPropietari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("Vehicle", jPanel1);

        jLabel10.setText("Numero Polissa");

        jLabel11.setText("DNI Prenedor");

        jLabel12.setText("Matricula Vehicle");

        jLabel13.setText("Data Inici");

        jLabel14.setText("Data Fi");

        jLabel15.setText("Tipus");

        cbTipusPolissa.setModel(new DefaultComboBoxModel(Polissa.TipusPolissa.values()));

        btBuscarXNumPolissa.setText("Buscar per Numero Polissa");
        btBuscarXNumPolissa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarXNumPolissaActionPerformed(evt);
            }
        });

        btInserirPolissa.setText("Inserir");
        btInserirPolissa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirPolissaActionPerformed(evt);
            }
        });

        btModificarPolissa.setText("Modificar");
        btModificarPolissa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarPolissaActionPerformed(evt);
            }
        });

        btEliminarPolissa.setText("Eliminar");
        btEliminarPolissa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarPolissaActionPerformed(evt);
            }
        });

        btMostrarTotesPolisses.setText("Mostrar Tots");
        btMostrarTotesPolisses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarTotesPolissesActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Numero Polissa", "DNI Prenedor", "Matricula Vehicle", "Data Inici", "Data Fi", "Tipus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jLabel16.setText("Import Prima");

        jTextPane1.setText("Important ! Les dates en format YYYY-MM-DD");
        jScrollPane4.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cbTipusPolissa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eTNumeroPolissa)
                    .addComponent(eTDNIPrenedor)
                    .addComponent(eTPolissaMatriculaVehicle)
                    .addComponent(eTDataInici)
                    .addComponent(eTDataFi)
                    .addComponent(eTPrima))
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btBuscarXNumPolissa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btInserirPolissa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btModificarPolissa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btEliminarPolissa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btMostrarTotesPolisses, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(eTNumeroPolissa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(eTDNIPrenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(eTPolissaMatriculaVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(eTDataInici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btBuscarXNumPolissa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btInserirPolissa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btModificarPolissa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btEliminarPolissa)
                        .addGap(13, 13, 13)
                        .addComponent(btMostrarTotesPolisses)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(eTDataFi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(eTPrima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(cbTipusPolissa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("Polisses", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarXNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarXNomActionPerformed
        Client_Controller client_Control = new Client_Controller();
        try {
            Client c = client_Control.Buscar(eTNif.getText());
            eTNom.setText(c.getNom());
            eTNif.setText(c.getNif());
            eTCarrer.setText(c.getAdreca().getCarrer());
            eTNumero.setText(String.valueOf(c.getAdreca().getNumero()));
            eTPoblacio.setText(c.getAdreca().getPoblacio());
        } catch (NoResultException ex) {
            JOptionPane.showMessageDialog(this, "Sense resultats");
        }
    }//GEN-LAST:event_btBuscarXNomActionPerformed

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed
        Client_Controller client_Control = new Client_Controller();
        Polissa_Controller pc = new Polissa_Controller();
        Vehicle_Controller vc = new Vehicle_Controller();
        try {
            Client client = client_Control.Buscar(eTNif.getText());
            
            List<Polissa> polisses = pc.ConsultaXClient(client);
            for (Polissa polisse : polisses) {
                pc.Eliminar(polisse);
            }
            
            List<Vehicle> vehicles = vc.ConsultaXClient(client);
            for (Vehicle vehicle : vehicles) {
                vc.Eliminar(vehicle);
            }
           
            client_Control.Eliminar(client);
            JOptionPane.showMessageDialog(this, "Eliminat");

        } catch (PersistenceException ex) {
            JOptionPane.showMessageDialog(this, "Fallo.");
        }
    }//GEN-LAST:event_btEliminarActionPerformed

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed
        Adreca adreca = new Adreca(eTCarrer.getText(), Integer.parseInt(eTNumero.getText()), eTPoblacio.getText());
        Client client = new Client(eTNif.getText(), eTNom.getText());
        client.setAdreca(adreca);
        Client_Controller client_Control = new Client_Controller();

        try {
            client_Control.Insertar(client);
            JOptionPane.showMessageDialog(this, "Inserit");

        } catch (PersistenceException ex) {
            JOptionPane.showMessageDialog(this, "Fallo. Elemento duplicado");
        }
    }//GEN-LAST:event_btInserirActionPerformed

    private void btModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarActionPerformed
        Client_Controller client_Control = new Client_Controller();
        try {
            Client client = client_Control.Buscar(eTNif.getText());
            client.setAdreca(new Adreca(eTCarrer.getText(), Integer.valueOf(eTNumero.getText()), eTPoblacio.getText()));
            client.setNom(eTNom.getText());
            client_Control.Modificar(client);
            JOptionPane.showMessageDialog(this, "Modificat");
        } catch (NoResultException ex) {
            JOptionPane.showMessageDialog(this, "Sense resultats");
        }
    }//GEN-LAST:event_btModificarActionPerformed

    private void btBuscarTotsClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarTotsClientsActionPerformed
        Client_Controller pc = new Client_Controller();
        List<Client> ConsultaTots = pc.ConsultaTots();
        String col[] = {"Nom", "Nif", "Carrer", "Numero", "Poblacio"};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0);
        for (Client p : ConsultaTots) {
            Object[] data = {
                p.getNom(),
                p.getNif(),
                p.getAdreca().getCarrer(),
                p.getAdreca().getNumero(),
                p.getAdreca().getPoblacio()
            };
            tableModel.addRow(data);
        }
        jTable1.setModel(tableModel);
    }//GEN-LAST:event_btBuscarTotsClientsActionPerformed

    private void btBuscarXMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarXMatriculaActionPerformed
        Vehicle_Controller vc = new Vehicle_Controller();
        try {
            Vehicle v = vc.Buscar(eTMatricula.getText());
            eTMatricula.setText(v.getMatricula());
            eTMarca.setText(v.getMarca());
            eTAnyMatriculacio.setText(String.valueOf(v.getAnyMatriculacio()));
            eTDNIPropietari.setText(v.getPropietari().getNif());
        } catch (NoResultException ex) {
            JOptionPane.showMessageDialog(this, "Sense resultats");
        }
    }//GEN-LAST:event_btBuscarXMatriculaActionPerformed

    private void btInserirVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirVehicleActionPerformed
        int LLARGADA_MAXIMA_MATRICULA = 7;
        if (eTMatricula.getText().length() <= LLARGADA_MAXIMA_MATRICULA) {
            Vehicle_Controller vc = new Vehicle_Controller();
            Client_Controller cc = new Client_Controller();
            try {
                Client propietari = cc.Buscar(eTDNIPropietari.getText());
                Vehicle v = new Vehicle(eTMatricula.getText().toUpperCase(), eTMarca.getText().toUpperCase(), Integer.valueOf(eTAnyMatriculacio.getText()), propietari);
                vc.Insertar(v);
                JOptionPane.showMessageDialog(this, "Inserit");
            } catch (NoResultException ex) {
                JOptionPane.showMessageDialog(this, "Error. No existeix aquest propietari a la BBDD");
            } catch (PersistenceException ex) {
                JOptionPane.showMessageDialog(this, "Error. Element duplicat");
            }
        } else {
            JOptionPane.showMessageDialog(this, "La matricula pot tenir un maxim de 7 caracters");
        }
    }//GEN-LAST:event_btInserirVehicleActionPerformed

    private void btModificarVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarVehicleActionPerformed
        Vehicle_Controller vc = new Vehicle_Controller();
        Client_Controller cc = new Client_Controller();
        try {
            Vehicle v = vc.Buscar(eTMatricula.getText().toUpperCase());
            v.setMarca(eTMarca.getText().toUpperCase());
            v.setAnyMatriculacio(Integer.valueOf(eTAnyMatriculacio.getText()));
            v.setPropietari(cc.Buscar(eTDNIPropietari.getText()));
            vc.Modificar(v);
            JOptionPane.showMessageDialog(this, "Modificat");
        } catch (NoResultException ex) {
            JOptionPane.showMessageDialog(this, "Sense resultats");
        }
    }//GEN-LAST:event_btModificarVehicleActionPerformed

    private void btEliminarVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarVehicleActionPerformed
        Vehicle_Controller vc = new Vehicle_Controller();
        Polissa_Controller pc = new Polissa_Controller();
        try {
            Vehicle v = vc.Buscar(eTMatricula.getText());
            
            List<Polissa> polisses = pc.ConsultaXVehicle(v);
            for (Polissa polisse : polisses) {
                pc.Eliminar(polisse);
            }
            
            vc.Eliminar(v);
            JOptionPane.showMessageDialog(this, "Eliminat");
        } catch (PersistenceException ex) {
            JOptionPane.showMessageDialog(this, "Fallo.");
        }
    }//GEN-LAST:event_btEliminarVehicleActionPerformed

    private void btMostrarTotsVehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarTotsVehiclesActionPerformed
        Vehicle_Controller vc = new Vehicle_Controller();
        List<Vehicle> ConsultaTots = vc.ConsultaTots();
        String col[] = {"Matricula", "Marca", "Any Matriculació", "DNI Propietari"};
        DefaultTableModel tableModel2 = new DefaultTableModel(col, 0);
        for (Vehicle v : ConsultaTots) {
            Object[] data = {
                v.getMatricula(),
                v.getMarca(),
                String.valueOf(v.getAnyMatriculacio()),
                v.getPropietari().getNif()
            };
            tableModel2.addRow(data);
        }
        jTable2.setModel(tableModel2);
    }//GEN-LAST:event_btMostrarTotsVehiclesActionPerformed

    private void btBuscarXNumPolissaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarXNumPolissaActionPerformed
        Polissa_Controller pc = new Polissa_Controller();
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
            Polissa p = pc.Buscar(eTNumeroPolissa.getText());
            eTDNIPrenedor.setText(p.getPrenedor().getNif());
            eTPolissaMatriculaVehicle.setText(p.getVehicle().getMatricula());
            eTDataInici.setText(sdf.format(p.getDataInici()));
            eTDataFi.setText(sdf.format(p.getDataFi()));
            eTPrima.setText(String.valueOf(p.getPrima()));
            cbTipusPolissa.setSelectedItem(p.getTipus());

        } catch (NoResultException ex) {
            JOptionPane.showMessageDialog(this, "Sense resultats");
        }
    }//GEN-LAST:event_btBuscarXNumPolissaActionPerformed

    private void btInserirPolissaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirPolissaActionPerformed

        try {
            SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
            Client_Controller client_Control = new Client_Controller();
            Client client = client_Control.Buscar(eTDNIPrenedor.getText());
            Vehicle_Controller vc = new Vehicle_Controller();
            Vehicle vehicle = vc.Buscar(eTPolissaMatriculaVehicle.getText());
            Date dateInici = sdf.parse(eTDataInici.getText());
            Date dateFi = sdf.parse(eTDataFi.getText());
            Polissa_Controller pc = new Polissa_Controller();
            Polissa polissa = new Polissa();
            polissa.setNumeroPolissa(eTNumeroPolissa.getText());
            polissa.setPrenedor(client);
            polissa.setVehicle(vehicle);
            polissa.setDataInici(dateInici);
            polissa.setDataFi(dateFi);
            polissa.setTipus(Polissa.TipusPolissa.valueOf(cbTipusPolissa.getSelectedItem().toString()));
            polissa.setPrima(Double.valueOf(eTPrima.getText()));
            pc.Insertar(polissa);
            JOptionPane.showMessageDialog(this, "Polissa inserida.");
        } catch (ParseException ex) {
            Logger.getLogger(inicia.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (PersistenceException ex) {
            JOptionPane.showMessageDialog(this, "Fallo. Elemento duplicado");
        }
    }//GEN-LAST:event_btInserirPolissaActionPerformed

    private void btModificarPolissaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarPolissaActionPerformed
        Polissa_Controller pc= new Polissa_Controller();
        Vehicle_Controller vc = new Vehicle_Controller();
        Client_Controller cc = new Client_Controller();
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
            Vehicle v = vc.Buscar(eTPolissaMatriculaVehicle.getText().toUpperCase());
            Client prenedor = cc.Buscar(eTDNIPrenedor.getText());
            
            Polissa p= pc.Buscar(eTNumeroPolissa.getText());
            Date dateInici = sdf.parse(eTDataInici.getText());
            Date dateFi = sdf.parse(eTDataFi.getText());
            
            p.setPrenedor(prenedor);
            p.setVehicle(v);
            p.setDataInici(dateInici);
            p.setDataFi(dateFi);
            p.setTipus(Polissa.TipusPolissa.valueOf(cbTipusPolissa.getSelectedItem().toString()));
            p.setPrima(Double.valueOf(eTPrima.getText()));
            System.out.println("INICI MODIFICACIO POLISSA");
            pc.Modificar(p);
            JOptionPane.showMessageDialog(this, "Modificat");
        } catch (NoResultException ex) {
            JOptionPane.showMessageDialog(this, "Sense resultats");
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Format de dates incorrecte");
        }
    
    }//GEN-LAST:event_btModificarPolissaActionPerformed

    private void btEliminarPolissaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarPolissaActionPerformed
        Polissa_Controller pc = new Polissa_Controller();
        try {
            Polissa p = pc.Buscar(eTNumeroPolissa.getText());
            pc.Eliminar(p);
            JOptionPane.showMessageDialog(this, "Eliminat");
        } catch (PersistenceException ex) {
            JOptionPane.showMessageDialog(this, "Fallo.");
        }
    }//GEN-LAST:event_btEliminarPolissaActionPerformed

    private void btMostrarTotesPolissesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarTotesPolissesActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
        Polissa_Controller pc = new Polissa_Controller();
        List<Polissa> ConsultaTots = pc.ConsultaTots();
        String col[] = {"Numero Polissa", "DNI Prendedor", "Matricula Vehicle",
            "DataInici", "DataFi", "Prima", "Tipus"};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0);
        for (Polissa p : ConsultaTots) {
            Object[] data = {
                p.getNumeroPolissa(),
                p.getPrenedor().getNif(),
                p.getVehicle().getMatricula(),
                sdf.format(p.getDataInici().getTime()),
                sdf.format(p.getDataFi().getTime()),
                p.getPrima(),
                p.getTipus().toString()
            };
            tableModel.addRow(data);
        }
        jTable3.setModel(tableModel);
    }//GEN-LAST:event_btMostrarTotesPolissesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarTotsClients;
    private javax.swing.JButton btBuscarXMatricula;
    private javax.swing.JButton btBuscarXNom;
    private javax.swing.JButton btBuscarXNumPolissa;
    private javax.swing.JButton btEliminar;
    private javax.swing.JButton btEliminarPolissa;
    private javax.swing.JButton btEliminarVehicle;
    private javax.swing.JButton btInserir;
    private javax.swing.JButton btInserirPolissa;
    private javax.swing.JButton btInserirVehicle;
    private javax.swing.JButton btModificar;
    private javax.swing.JButton btModificarPolissa;
    private javax.swing.JButton btModificarVehicle;
    private javax.swing.JButton btMostrarTotesPolisses;
    private javax.swing.JButton btMostrarTotsVehicles;
    private javax.swing.JComboBox cbTipusPolissa;
    private javax.swing.JTextField eTAnyMatriculacio;
    private javax.swing.JTextField eTCarrer;
    private javax.swing.JTextField eTDNIPrenedor;
    private javax.swing.JTextField eTDNIPropietari;
    private javax.swing.JTextField eTDataFi;
    private javax.swing.JTextField eTDataInici;
    private javax.swing.JTextField eTMarca;
    private javax.swing.JTextField eTMatricula;
    private javax.swing.JTextField eTNif;
    private javax.swing.JTextField eTNom;
    private javax.swing.JTextField eTNumero;
    private javax.swing.JTextField eTNumeroPolissa;
    private javax.swing.JTextField eTPoblacio;
    private javax.swing.JTextField eTPolissaMatriculaVehicle;
    private javax.swing.JTextField eTPrima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
